# Generated by Django 5.2.11 on 2026-02-27 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleoauthprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='googleoauthprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='googleoauthprofile',
            name='google_sub',
        ),
        migrations.RemoveField(
            model_name='googleoauthprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='googleoauthprofile',
            name='token_expiry',
        ),
        migrations.RemoveField(
            model_name='googleoauthprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='googleoauthprofile',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='googleoauthprofile',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googleoauthprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='googleoauthprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
